SHOW_SUSPICIOUS_CUSTOMERS = "SHOW_SUSPICIOUS_CUSTOMERS"

SHOW_CRYPTO_TRANSACTIONS = "SHOW_CRYPTO_TRANSACTIONS"

SHOW_HIGH_VALUE_TRANSACTIONS = "SHOW_HIGH_VALUE_TRANSACTIONS"

INVESTIGATE_CUSTOMER = "INVESTIGATE_CUSTOMER"

EXPLAIN_RISK = "EXPLAIN_RISK"